"""empty message

Revision ID: e8849f1d615a
Revises: 8d4280d377e2
Create Date: 2026-05-17 02:01:17.987139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8849f1d615a'
down_revision: Union[str, Sequence[str], None] = '8d4280d377e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('events_weekly_id_fkey'), 'events', type_='foreignkey')
    op.create_foreign_key(None, 'events', 'weekly_events', ['weekly_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.create_foreign_key(op.f('events_weekly_id_fkey'), 'events', 'weekly_events', ['weekly_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
