"""add_color_to_events

Revision ID: 459a898082b5
Revises: aca6618f996c
Create Date: 2026-01-04 14:12:25.210225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '459a898082b5'
down_revision: Union[str, Sequence[str], None] = 'aca6618f996c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('color', sa.String(length=6), nullable=False, server_default='4CAF50'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'color')
    # ### end Alembic commands ###
