"""empty message

Revision ID: 056a12d50cd9
Revises: cb0e6559d7e1
Create Date: 2026-01-13 10:53:13.692135

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "056a12d50cd9"
down_revision: Union[str, Sequence[str], None] = "cb0e6559d7e1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("gender", sa.String(), nullable=True))
    op.add_column("users", sa.Column("phone", sa.String(), nullable=True))
    op.add_column("visits", sa.Column("uid", sa.String(), nullable=False))
    op.add_column("visits", sa.Column("event_id", sa.Integer(), nullable=True))
    op.alter_column("visits", "timestamp", existing_type=postgresql.TIMESTAMP(), nullable=False)
    op.create_foreign_key(None, "visits", "events", ["event_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "visits", type_="foreignkey")
    op.alter_column("visits", "timestamp", existing_type=postgresql.TIMESTAMP(), nullable=True)
    op.drop_column("visits", "event_id")
    op.drop_column("visits", "uid")
    op.drop_column("users", "phone")
    op.drop_column("users", "gender")
    # ### end Alembic commands ###
