"""empty message

Revision ID: c09a8ef7c5da
Revises: e8849f1d615a
Create Date: 2026-05-17 10:27:13.959967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c09a8ef7c5da'
down_revision: Union[str, Sequence[str], None] = 'e8849f1d615a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('events_weekly_id_fkey'), 'events', type_='foreignkey')
    op.create_foreign_key(None, 'events', 'weekly_events', ['weekly_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('visits_trainer_id_fkey'), 'visits', type_='foreignkey')
    op.drop_constraint(op.f('visits_user_id_fkey'), 'visits', type_='foreignkey')
    op.drop_constraint(op.f('visits_event_id_fkey'), 'visits', type_='foreignkey')
    op.create_foreign_key(None, 'visits', 'trainers', ['trainer_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'visits', 'users', ['user_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'visits', 'events', ['event_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'visits', type_='foreignkey')
    op.drop_constraint(None, 'visits', type_='foreignkey')
    op.drop_constraint(None, 'visits', type_='foreignkey')
    op.create_foreign_key(op.f('visits_event_id_fkey'), 'visits', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('visits_user_id_fkey'), 'visits', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('visits_trainer_id_fkey'), 'visits', 'trainers', ['trainer_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.create_foreign_key(op.f('events_weekly_id_fkey'), 'events', 'weekly_events', ['weekly_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
