"""empty message

Revision ID: 8d4280d377e2
Revises: f00e7df9c0be
Create Date: 2026-05-17 00:40:01.477523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d4280d377e2'
down_revision: Union[str, Sequence[str], None] = 'f00e7df9c0be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weekly_events', sa.Column('price', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weekly_events', 'price')
    # ### end Alembic commands ###
