"""add qr attendance system

Revision ID: 8f6400caec9b
Revises: e20434a4db5e
Create Date: 2026-05-16 12:25:43.150976

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8f6400caec9b"
down_revision: Union[str, Sequence[str], None] = "e20434a4db5e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("users_rfid_uid_key"), "users", type_="unique")
    op.drop_column("users", "rfid_uid")
    op.create_unique_constraint(None, "visits", ["user_id", "event_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "visits", type_="unique")
    op.add_column("users", sa.Column("rfid_uid", sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint(
        op.f("users_rfid_uid_key"), "users", ["rfid_uid"], postgresql_nulls_not_distinct=False
    )
    # ### end Alembic commands ###
