"""empty message

Revision ID: f00e7df9c0be
Revises: c446f2d57585
Create Date: 2026-05-16 22:55:27.101899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f00e7df9c0be'
down_revision: Union[str, Sequence[str], None] = 'c446f2d57585'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visits', sa.Column('trainer_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'visits', 'trainers', ['trainer_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'visits', type_='foreignkey')
    op.drop_column('visits', 'trainer_id')
    # ### end Alembic commands ###
